"""Application metadata and stable defaults."""

_APP_DISPLAY_NAME = "CYOA Downloader"
_APP_VERSION = "1.0.5"
_STABILIZATION_PATCH_ID = "CYOA-v1.0.5"
_GITHUB_RELEASE_API = ""

DEFAULT_WAIT_TIME = 60
DEFAULT_MAX_WORKERS = 4

__all__ = [
    "_APP_DISPLAY_NAME", "_APP_VERSION", "_STABILIZATION_PATCH_ID", "_GITHUB_RELEASE_API",
    "DEFAULT_WAIT_TIME", "DEFAULT_MAX_WORKERS",
]
